// generated by Fast Light User Interface Designer (fluid) version 1.0102

#ifndef RobotUI_h
#define RobotUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include "Robot.h"

class RobotUI {
public:
  RobotUI();
private:
  Fl_Double_Window *mainWindow;
public:
  Fl_Group *VChange;
  Fl_Group *HChange;
  Fl_Group *MainView;
  Robot *cube;
  void show(int argc, char **argv);
};
#endif
