// generated by Fast Light User Interface Designer (fluid) version 1.0102

#include "RobotUI.h"
// added after getting fed up with fltk
#define SIZE 900
RobotUI::RobotUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mainWindow = new Fl_Double_Window(SIZE, SIZE, "Marvin the robot");
    w = o;
    o->box(FL_UP_BOX);
    o->labelsize(12);
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(-5, -9, SIZE, SIZE);
      { Fl_Group* o = VChange = new Fl_Group(5, SIZE, 37, SIZE);
        o->end();
      }
      { Fl_Group* o = HChange = new Fl_Group(120, 362, 190, 40);
        o->end();
      }
      { Fl_Group* o = MainView = new Fl_Group(-5, -9, SIZE, SIZE);
        { Robot* o = cube = new Robot(-5, -9, SIZE, SIZE, "This is the cube_view");
          o->box(FL_NO_BOX);
          o->color(49);
          o->selection_color(49);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(56);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      o->end();
    }
    o->end();
  }
}

void RobotUI::show(int argc, char **argv) {
  mainWindow->show(argc, argv);
}
